var moduleFunctionMap = 
    {'GDI32': ['GetMapMode',
            'Escape',
            'ExtTextOutA',
            'TextOutA',
            'RectVisible',
            'PtVisible',
            'BitBlt',
            'CreateCompatibleBitmap',
            'LPtoDP',
            'CreateCompatibleDC',
            'GetBkColor',
            'DPtoLP',
            'GetViewportExtEx',
            'GetWindowExtEx'],
    'KERNEL32': ['GetStartupInfoA',
                'GetModuleHandleA',
                'LoadLibraryExW',
                'FindResourceA',
                'SizeofResource',
                'LoadResource'],
    'Library': ['Name'],
    'MFC42': ['CFrameWnd::PostNcDestroy',
            'CWnd::DefWindowProcA',
            'CWnd::OnWndMsg',
            'CWnd::WindowProc',
            'CWnd::OnAmbientProperty',
            'CFrameWnd::PreTranslateMessage',
            'CFrameWnd::EndModalState',
            'CFrameWnd::BeginModalState',
            'CWnd::GetSuperWndProcAddr',
            'CWnd::OnNotify',
            'CFrameWnd::OnCommand',
            'CWnd::EndModalLoop',
            'CWnd::ContinueModal',
            'CWnd::WinHelpA',
            'CWnd::GetScrollBarCtrl',
            'CWnd::OnToolHitTest',
            'CWnd::CalcWindowRect',
            'CWnd::DestroyWindow',
            'CWnd::Create',
            'CWnd::PreSubclassWindow',
            'CCmdTarget::GetConnectionHook',
            'CCmdTarget::GetExtraConnectionPoints',
            'CCmdTarget::GetInterfaceHook',
            'CCmdTarget::OnCreateAggregates',
            'CCmdTarget::GetEventSinkMap',
            'CCmdTarget::GetInterfaceMap',
            'CCmdTarget::GetConnectionMap',
            'CCmdTarget::GetDispatchMap',
            'CCmdTarget::GetCommandMap',
            'CCmdTarget::GetTypeLib',
            'CCmdTarget::GetTypeLibCache',
            'CCmdTarget::GetTypeInfoCount',
            'CCmdTarget::GetDispatchIID',
            'CCmdTarget::IsInvokeAllowed',
            'CWnd::OnFinalRelease',
            'CFrameWnd::OnCmdMsg',
            'CToolBar::~CToolBar',
            'CFrameWnd::~CFrameWnd',
            'CDialogBar::CDialogBar',
            'CReBar::CReBar',
            'CToolBar::CToolBar',
            'CFrameWnd::CFrameWnd',
            'operator delete',
            'CControlBar::~CControlBar',
            'CDialogBar::~CDialogBar',
            'CControlBar::SetBarStyle',
            'CReBar::AddBar',
            'CReBar::Create',
            'CToolBar::LoadToolBar',
            'CToolBar::CreateEx',
            'CFrameWnd::OnCreate',
            'CFrameWnd::PreCreateWindow',
            'CWinApp::OnFileOpen',
            'CWinApp::OnFileNew',
            'AFX_MSGMAP const CWinApp::messageMap',
            'CWinApp::WinHelpA',
            'CWinApp::OnDDECommand',
            'CWinApp::DoWaitCursor',
            'CWinApp::DoMessageBox',
            'CWinApp::SaveAllModified',
            'CWinApp::InitApplication',
            'CWinApp::AddToRecentFileList',
            'CWinApp::OpenDocumentFile',
            'CWinThread::Delete',
            'CWinThread::GetMainWnd',
            'CWinThread::ProcessMessageFilter',
            'CWinApp::ProcessWndProcException',
            'CWinApp::ExitInstance',
            'CWinThread::IsIdleMessage',
            'CWinApp::OnIdle',
            'CWinThread::PumpMessage',
            'CWinThread::PreTranslateMessage',
            'CWinApp::Run',
            'CCmdTarget::OnFinalRelease',
            'CCmdTarget::OnCmdMsg',
            'CWinApp::GetRuntimeClass',
            'CWinApp::~CWinApp',
            'COleTemplateServer::COleTemplateServer',
            'CWinApp::CWinApp',
            'COleObjectFactory::~COleObjectFactory',
            'COleObjectFactory::RegisterAll',
            'CWnd::ShowWindow',
            'CCommandLineInfo::~CCommandLineInfo',
            'CWinApp::ProcessShellCommand',
            'COleObjectFactory::UpdateRegistryAll',
            'COleTemplateServer::UpdateRegistry',
            'CWinApp::ParseCommandLine',
            'CCommandLineInfo::CCommandLineInfo',
            'COleTemplateServer::ConnectTemplate',
            'CWinApp::AddDocTemplate',
            'CSingleDocTemplate::CSingleDocTemplate',
            'CWinApp::LoadStdProfileSettings',
            'CWinApp::SetRegistryKey',
            'CWinApp::Enable3dControls',
            'AfxEnableControlContainer',
            'AfxMessageBox',
            'AfxOleInit',
            'CDialog::PreInitDialog',
            'CDialog::OnCancel',
            'CDialog::OnOK',
            'CDialog::OnSetFont',
            'CDialog::OnInitDialog',
            'CDialog::DoModal',
            'CDialog::SetOccDialogInfo',
            'CWnd::IsFrameWnd',
            'CDialog::CheckAutoCenter',
            'CWnd::PostNcDestroy',
            'CDialog::PreTranslateMessage',
            'CWnd::OnCommand',
            'CWnd::PreCreateWindow',
            'CDialog::OnCmdMsg',
            'CWnd::OnChildNotify',
            'CDialog::CDialog',
            'CDialog::~CDialog',
            'AFX_MSGMAP const CDialog::messageMap',
            'CRuntimeClass const CDocument::classCDocument',
            'AFX_MSGMAP const CDocument::messageMap',
            'AFX_DISPMAP const CCmdTarget::dispatchMap',
            'AFX_INTERFACEMAP const CCmdTarget::interfaceMap',
            'CDocument::OnIdle',
            'CDocument::GetDefaultAccelerator',
            'CDocument::GetDefaultMenu',
            'CDocument::UpdateFrameCounts',
            'CDocument::DoFileSave',
            'CDocument::DoSave',
            'CDocument::PreCloseFrame',
            'CDocument::SaveModified',
            'CDocument::CanCloseFrame',
            'CDocument::ReleaseFile',
            'CDocument::GetFile',
            'CDocument::ReportSaveLoadException',
            'CDocument::OnCloseDocument',
            'CDocument::OnSaveDocument',
            'CDocument::OnOpenDocument',
            'CDocument::DeleteContents',
            'CDocument::OnChangedViewList',
            'CDocument::GetNextView',
            'CDocument::GetFirstViewPosition',
            'CDocument::SetPathName',
            'CDocument::SetTitle',
            'CDocument::OnFinalRelease',
            'CDocument::OnCmdMsg',
            'CDocument::~CDocument',
            'AfxOleLockApp',
            'CCmdTarget::EnableAutomation',
            'CDocument::CDocument',
            'AfxOleUnlockApp',
            'CDocument::OnNewDocument',
            'CRuntimeClass const CView::classCView',
            'AFX_MSGMAP const CView::messageMap',
            'CView::OnEndPrintPreview',
            'CView::OnEndPrinting',
            'CView::OnPrint',
            'CView::OnBeginPrinting',
            'CView::OnPreparePrinting',
            'CView::OnUpdate',
            'CView::OnActivateFrame',
            'CView::OnActivateView',
            'CView::OnDragScroll',
            'CView::OnDropEx',
            'CView::OnDrop',
            'CView::OnDragLeave',
            'CView::OnDragOver',
            'CView::OnDragEnter',
            'CView::OnScrollBy',
            'CView::OnScroll',
            'CView::IsSelected',
            'CView::PostNcDestroy',
            'CWnd::PreTranslateMessage',
            'CView::GetScrollBarCtrl',
            'CView::CalcWindowRect',
            'CView::OnCmdMsg',
            'CObject::GetRuntimeClass',
            'CView::CView',
            'CView::~CView',
            'CView::PreCreateWindow',
            'CString::CString',
            'CBitmap::GetRuntimeClass',
            'CDC::GetClipBox',
            'CDC::ScaleWindowExt',
            'CDC::SetWindowExt',
            'CDC::ScaleViewportExt',
            'CDC::SetViewportExt',
            'CDC::OffsetViewportOrg',
            'CDC::SetViewportOrg',
            'CDC::SetTextColor',
            'CDC::SetBkColor',
            'CDC::SelectObject',
            'CDC::SelectStockObject',
            'CDC::RestoreDC',
            'CDC::SaveDC',
            'CDC::ReleaseOutputDC',
            'CDC::ReleaseAttribDC',
            'CDC::SetOutputDC',
            'CDC::SetAttribDC',
            'CDC::GetRuntimeClass',
            'CDC::~CDC',
            'CDC::SelectGdiObject',
            'CDC::SetWindowOrg',
            'CDC::SetMapMode',
            'CGdiObject::Attach',
            'CDC::Attach',
            'CDC::CDC',
            'CString::~CString',
            'CDC::SetTextAlign',
            'CDC::SetBkMode',
            'CDC::FillSolidRect',
            'CWnd::Default',
            'CView::OnPrepareDC',
            'CView::OnInitialUpdate',
            'CPen::CPen',
            'CDC::LineTo',
            'CDC::MoveTo',
            'CDC::SelectObject',
            'CGdiObject::GetRuntimeClass',
            'CGdiObject::DeleteObject',
            'CClientDC::~CClientDC',
            'CClientDC::CClientDC',
            'CArchive::Read',
            'CArchive::Write',
            'CArchive::ReadCount',
            'CArchive::WriteCount',
            'AfxWinMain',
            'CWnd::CheckAutoCenter',
            'CFrameWnd::IsFrameWnd',
            'CWnd::SetOccDialogInfo',
            'CFrameWnd::LoadFrame',
            'CFrameWnd::GetActiveDocument',
            'CFrameWnd::GetActiveFrame',
            'CFrameWnd::GetMessageString',
            'CFrameWnd::RecalcLayout',
            'CFrameWnd::ActivateFrame',
            'CFrameWnd::OnSetPreviewMode',
            'CFrameWnd::GetMessageBar',
            'CFrameWnd::NegotiateBorderSpace',
            'CFrameWnd::OnCreateClient',
            'CFrameWnd::OnUpdateFrameTitle',
            'CFrameWnd::OnUpdateFrameMenu',
            'CFrameWnd::GetDefaultAccelerator',
            'CFrameWnd::DelayUpdateFrameMenu',
            'CFrameWnd::ExitHelpMode',
            'AFX_MSGMAP const CFrameWnd::messageMap',
            'CRuntimeClass const CFrameWnd::classCFrameWnd',
            'CDialog::GetRuntimeClass',
            'operator new',
            'AfxGetModuleState'],
    'MSVCP60': ['std::ios_base::Init::Init',
                'std::_Winit::_Winit',
                'std::_Winit::~_Winit',
                //'std::endl',
                'std::operator<<',
                'std::basic_ostream<char,std::char_traits<char>> std::cout',
                'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::~basic_string<char,std::char_traits<char>,std::allocator<char>>',
                'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Eos',
                'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Grow',
                'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Tidy',
                'std::ios_base::Init::~Init'],
    'MSVCRT': ['__CxxFrameHandler',
                '__setusermatherr',
                '_adjust_fdiv',
                // '__p__commode',
                // '__p__fmode',
                // '__set_app_type',
                // '_except_handler3',
                // '_initterm',
                // '__getmainargs',
                // '_acmdln',
                'exit',
                // '_XcptFilter',
                '_exit',
                '_onexit',
                '__dllonexit',
                '_ftol',
                '_purecall',
                'memmove',
                'time',
                'srand',
                'rand',
                'printf',
                '_setmbcp',
                // '_controlfp'
            ],
    'USER32': ['GrayStringA',
                'DrawTextA',
                'TabbedTextOutA',
                'KillTimer',
                'PtInRect',
                'SetTimer',
                'InvalidateRect',
                'GetClientRect',
                'EnableWindow',
                'UpdateWindow',
                //'GetWindowTextA'
            ]}

/* for (var dllName in moduleFunctionMap) {
    log_message("dllName: " + dllName)
    hookFunctionNames(dllName, moduleFunctionMap[dllName])
} */
